<?php

namespace w1575;

use w1575\ConsoleColor;
use yii\base\Behavior;

class ConsoleColorBehavior extends Behavior
{
    /**
     * @var собственно сам компонет будет хранится здесь
     */
    public $c;

    public $theme = 'invert';

    public function init()
    {
        $this->c = new ConsoleColor($this->theme);
        parent::init(); // TODO: Change the autogenerated stub
    }


}


